app/apps/web/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.auth import views as auth_base_views
from django.views.decorators.cache import cache_page

from apps.web.views.main import MainPage
from apps.web.views import auth as auth_views
from apps.web.views import dictionary as dictionary_views
from apps.web.views import word as word_views
from apps.web.views import repeat as repeat_views

urlpatterns = [
    path('', MainPage.as_view(), name="main"),
    path("logout/", auth_base_views.LogoutView.as_view(), name="logout"),
    # path("password_change/", auth_views.PasswordChangeView.as_view(), name="password_change"),
    # path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(), name="password_change_done",),
    # path("password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"),
    # path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name="password_reset_done",),
    # path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm",),
    # path("reset/done/", auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete",),
    path('login/', auth_views.LoginPage.as_view(), name="login"),
    path('registration/', auth_views.RegistrationPage.as_view(), name="registration"),
    path('dictionary/', dictionary_views.DictionaryPage.as_view(), name="dictionary"),
    path('dictionary/create/', dictionary_views.DictionaryCreatePage.as_view(), name="dictionary-create"),
    path('dictionary/upload/', dictionary_views.DictionaryUpload.as_view(), name="dictionary-upload"),
    path('dictionary/<int:id>/', dictionary_views.DictionaryDetailPage.as_view(), name="dictionary-detail"),
    path('dictionary/<int:id>/pin/', dictionary_views.DictionaryPin.as_view(), name="dictionary-pin"),
    path('dictionary/<int:id>/unpin/', dictionary_views.DictionaryUnpin.as_view(), name="dictionary-unpin"),
    path('dictionary/<int:id>/update/', dictionary_views.DictionaryUpdatePage.as_view(), name="dictionary-update"),
    path('dictionary/<int:id>/remove/', dictionary_views.DictionaryRemovePage.as_view(), name="dictionary-remove"),

    path('word/<int:id>/', word_views.word_template, name="word-form"),
    path('word/create/', word_views.WordCreatePage.as_view(), name="word-create"),
    path('word/<int:id>/delete/', word_views.WordDeletePage.as_view(), name="word-delete"),

    path('dictionary/<int:id>/repeat/', repeat_views.repeat, name="repeat"),
    path('dictionary/<int:id>/repeat/<str:session>/', repeat_views.RepeatPage.as_view(), name="repeat-page"),
]

app_name = "web"

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.web.urls", namespace="web")),
    path("api/", include("api.urls")),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^assets/(?P<path>.*)$', serve, {'document_root': settings.ASSETS_ROOT}),
]

# if settings.DEBUG:
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/web/templates/web/dictionary_create_page.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row ">
            <div class="col-md-12 col-lg-12 mt-3">
                {% include 'web/components/dictionary_creation.html' with form=form %}
            </div>
{#        <div class="col-md-12 col-lg-6 mt-3">#}
{#            <h4 class="d-flex justify-content-between align-items-center mb-3 text-responsive-mid">#}
{#              <span class="text-primary">Collabarate with</span>#}
{#            </h4>#}
{#            <form role="search" method="GET" action="collobarators">#}
{#                <div class="input-group mb-3">#}
{#                    <input name="search" type="search" class="form-control text-responsive-mid" placeholder="Search..." aria-label="Search">#}
{#                    <button class="btn btn-outline-secondary text-responsive-mid" type="submit" id="button-addon2">Search</button>#}
{#                </div>#}
{#            </form>#}
{##}
{#            <ul class="list-group mb-3">#}
{#                <li class="list-group-item d-flex justify-content-between lh-sm">#}
{#                    <div>#}
{#                        <h6 class="my-0 text-responsive-mid">Username</h6>#}
{#                    </div>#}
{#                    <button class="btn btn-success">Add</button>#}
{#                </li>#}
{#            </ul>#}
{##}
{#            <ul class="list-group mb-3">#}
{#                <li class="list-group-item d-flex justify-content-between lh-sm">#}
{#                    <div>#}
{#                        <h6 class="my-0 text-responsive-mid">Username</h6>#}
{#                    </div>#}
{#                    <button class="btn btn-danger"> Remove </button>#}
{#                </li>#}
{#            </ul>#}
{#        </div>#}
        </div>

        {% if form.id.value and form.id.value != 'None' %}
            <h4 class="mb-3 text-responsive">Words</h4>
            <div class="container">
                <div class="row" id="words">
                    {% for word in words %}
                        <div class="col-md-12 col-lg-4">
                            {% include 'web/components/word_creation.html' with form=word csrf_token=csrf_token %}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <hr class="my-4">

            <button class="btn btn-primary col-5 text-responsive-mid" type="button"
                    hx-get="{% url 'web:word-form' id=form.id.value %}"
                    hx-swap="beforeend" hx-target="#words">
                Add
            </button>
            <hr class="my-4">
        {% endif %}
    </div>
{% endblock %}

app/apps/web/templates/web/dictionary_detail_page.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                {% include 'web/components/dictionary_cart.html' with words=words %}
            </div>
        </div>
    </div>
{#    <h4>Words:</h4>#}
{#    <div class="container">#}
{#        <div class="row">#}
{#            {% for word in words %}#}
{#                <div class="col-lg-4">#}
{#                    {% include 'web/components/word_card_min.html' with form=word %}#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#    </div>#}
{% endblock %}

app/apps/web/templates/web/dictionary_page.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row text-center">
            {% for dictionary in dictionaries %}
                <div class="col-sm-12 col-lg-4 mb-4 text-center">
                    {% include "web/components/dictionary_cart.html" with limited=True %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/apps/web/templates/web/dictionary_upload.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="row justify-content-center">
        <div class="col col-lg-6">
            <form method="POST" class="mx-auto" enctype="multipart/form-data">
                {% csrf_token %}
                <input hidden name="key" value="{{ parsed.key }}">
                {% if not parsed.key %}
                    <label for="file_input">Insert file (accept for now only .json)</label>
                    <input type="file" id="file_input" class="form-control" name="file">
                    {{ form.file.errors }}
                    <button type="submit" class="btn btn-primary mt-2">Check file</button>
                {% else  %}
                    <h3>Select fields for rows:</h3>
                    <div class="container">
                        {% for row in parsed.data_example %}
                        <div class="row">
                            <div class="col-lg-5">
                                {{ row }}
                            </div>
                            <div class="col-lg-5">
                                <select class="form-select" name="fields{{ loop.index }}">
                                    <option value="word_from">word_from</option>
                                    <option value="word_from">word_to</option>
                                    <option value="word_from">transcription</option>
                              </select>
                            </div>
                        </div>
                        {% endfor %}
                        {{ form.fields.errors }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-2">Upload</button>
                {% endif %}
            </form>
        </div>
        </div>
    </div>

{% endblock %}

app/apps/web/templates/web/learning_page.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="progress mb-4">
          <div class="progress-bar" style="width: {{ form.progress }}%" role="progressbar" aria-valuenow="{{ form.progress }}" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col col-lg-6 mx-auto">
                    {% if form.type == 'cart' %}
                        {% include 'web/components/learning/word_card.html' with form=form.word type=form.type %}
                        <audio src="{{ form.word.prononsiation }}" autoplay></audio>
                    {% elif form.type == 'choice' %}
                        {% include 'web/components/learning/choices.html' with form=form %}
                        <audio src="{{ form.word.prononsiation }}" autoplay></audio>
                    {% elif form.type == 'choice_reverse' %}
                        {% include 'web/components/learning/choices_reverse.html' with form=form %}
                    {% elif form.type == 'word_builder' %}
                        {% include 'web/components/learning/word_build.html' with form=form %}
                    {% elif form.type == 'word_writer' %}
                        {% include 'web/components/learning/word_write.html' with form=form %}
                    {% elif form.type == 'finish' %}
                        {% include 'web/components/learning/finish.html' with form=form %}
                    {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/apps/web/templates/web/login_page.html
{% extends "base.html" %}

{% block header%}

{% endblock %}

{% block content %}
<div class="container d-flex align-items-center justify-content-center vh-100">
    <main class="text-center">
      <div class="col-md-auto col-lg-auto">
        <form method="POST">
          {% csrf_token %}
          <h1 class="h3 mb-3 fw-normal text-responsive">Please sign in</h1>

           <div>
            {% for type, error in form.error_messages.items %}
            <div class="alert alert-danger text-responsive-min" role="alert">
              {{ error }}
            </div>
            {% endfor %}
          </div>

          <div class="form-floating mt-3">
            <input type="email" class="form-control input-responsive text-responsive-mid" id="floatingInput" name="username" placeholder="name@example.com">
            <label for="floatingInput" class="text-responsive-mid">Email address</label>
          </div>
          <div class="form-floating mt-3">
            <input type="password" class="form-control input-responsive text-responsive-mid" id="floatingPassword" name="password" placeholder="Password">
            <label for="floatingPassword" class="text-responsive-mid">Password</label>
          </div>
          <button class="w-100 btn btn-lg btn-primary text-responsive-mid mt-3" type="submit">Sign in</button>
          <p class="mt-5 text-muted text-responsive-mid">© Language Learner</p>
        </form>
      </div>
    </main>
</div>
{% endblock %}

app/apps/web/templates/web/logout_page.html
{% extends "base.html" %}

{% block header%}

{% endblock %}

{% block content %}
<div class="container d-flex align-items-center justify-content-center vh-100">
    <main class="text-center">
      <div style="min-width: 300px;">
        <form>
          {% csrf_token %}
          <button class="w-100 btn btn-lg btn-primary" type="submit">Sign out</button>
          <p class="mt-5 mb-3 text-muted">© Language Learner</p>
        </form>
      </div>
    </main>
</div>
{% endblock %}

app/apps/web/templates/web/main_page.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row text-center">
            {% if user.is_authenticated %}
                <div class="mb-5">
                    <h1 class="fw-light text-responsive">Hello, {{ user.username }}
                    {% if progress %}
                        , your last week progress:
                    {% else %}
                         , here you will see your progress
                    {% endif %}
                    </h1>
                    {% if progress %}
                        <div class="row justify-content-center mt-3">
                            {% include 'web/components/progress_container.html' with progress=progress %}
                        </div>
                    {% endif %}
                </div>


                <h1 class="fw-light mb-3">Searching</h1>
                {% include 'web/components/searching.html' %}
            {% else %}
                <div style="margin-top: 10%;">
                    <h1 class="fw-light text-responsive">Dictionaries from users all over the world</h1>
                    <p class="lead text-muted text-responsive">You can simplify learning new languages from all over the world dictionaries.</p>
                    {% include 'web/components/searching.html' %}
                </div>

            {% endif %}
        </div>
    </div>
{% endblock %}

app/apps/web/templates/web/registration.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="raw justify-content-center">
        <div class="col col-lg-5 mx-auto">
            <form method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="email" class="form-label text-responsive">Email address</label>
                    <input type="email" class="form-control input-responsive text-responsive" id="email" name="email" placeholder="name@example.com" value="{{ form.email.value }}">
                    {{ form.email.errors }}
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label text-responsive">Username</label>
                    <input type="text" class="form-control input-responsive text-responsive" id="username" name="username" value="{{ form.username.value }}">
                    {{ form.username.errors }}
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label text-responsive">Password</label>
                    <input type="password" class="form-control input-responsive text-responsive" id="password" name="password" value="{{ form.password.value }}">
                    {{ form.password.errors }}
                </div>
                <div class="mb-3">
                    <label for="password-repeat" class="form-label text-responsive">Repeat password</label>
                    <input type="password" class="form-control input-responsive text-responsive" id="password-repeat" name="password_repeat" value="{{ form.password_repeat.value }}">
                    {{ form.password_repeat.errors }}
                </div>
                <button type="submit" class="btn btn-primary text-responsive-mid">Create new account</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}